### ISSUE TITLE
lineheight only for an entire line (paragraph) not for spans of characters?

### ISSUE THREAD

**Issue by stefanmintert** [ether/ep_line_height#1]
Hi John

I'd like to have line height control for an entire line, not for several parts of a line. How should I do this? Another plugin?

I think about writing my own plugin for that purpose. 

Thanks in advance for an answer!

Kind regards

Stefan

**Comment by JohnMcLear** [comment]
This plugin does do that, it processes line height for the entire line..

https://github.com/JohnMcLear/ep_line_height/blob/master/static/js/index.js#L47 --

What problem are you seeing?

**Comment by stefanmintert** [comment]
If I install the plugin via /admin I get a different version. Looks like the latest version isn't published:

https://www.npmjs.com/package/ep_line_height 
"0.0.2 is the latest of 2 releases"

https://github.com/JohnMcLear/ep_line_height/blob/master/package.json#L4
"version": "0.0.3"

**Comment by JohnMcLear** [comment]
Published, thanks! :)
